[build]
  publish = "dist"
  command = "pnpm run generate"

[[redirects]]
  from = "https://dachsbau.netlify.app/*"
  to = "https://dachsbau-tautenhain.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
