name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: cp .env.example .env

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build
        env:
          NITRO_PRESET: cloudflare
          KIRBY_BASE_URL: ${{ secrets.KIRBY_BASE_URL }}
          KIRBY_API_TOKEN: ${{ secrets.KIRBY_API_TOKEN }}

      - name: Deploy to Cloudflare
        run: npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
